appveyor:
  secure: {BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XlC9uAkjjl9DzY0Z2OaH86bJN0Q6K1/QJ1rEcBlZg7KBcgk+BUdYhpmk7Kbqtr8+lmbzCQcoHNGAZy28ksqkbIbRPBfnzhWlJPnWBtws96Nkm/XvHuY90hs2zAWTuHrMASUp8xYUv0ZPAChnH5vamllC32ecBGlwEuMvElMVMOTmKLNwlt/NjiWprRGwxRHHX7bZ0Ba1Z30Zka2umxLkJlCXXVy3QHTya7aG9c12J7bkSEvKXPHeehC0frHmwMmS3jNrkVDFI1SItbT07WqfGCVVJofl082YV+Eqyj8FZ9exKTEdOcwEyN09raMgdLjBm4qVoB1FK7r/qr22BAoIji6sdfMei6uRTSd5cZ5fm+GRa6GCOe9nc28FX/kr4xzqNw/D3WCYEgwDN1808zY5AHhq7tfGHa57TMbnI+TGxKeAgUXAEbIAlGq5dNAQLubnWGKZe+4x7Dg7QaJMDNRln2V324C/YAZ+2RY1urP35HeIM8kIzmQDhsfawx3zBVOLILWcJc8uYsGnkndz9dEqmimNQQPJRpvEnsXjXbY4PzhtPo9yKl6T3jqPj5x54RtG+JgjlmDZJ8drx2OKOgwR9kPp2W5HR3Mepfuq3UX6xMZjSisYmelCdawGaHLR7oAYhVTiPGdedbK6rayDaJS41LTwkx2CuFk1P2TOx6/YEb8=}
